Feature/xp bar
he4rt/he4rt-landing-ssr pull request #35
Opened 2023-01-25 13:29 UTC by cherryramatisdev

Solves #30 

Essa é minha proposta inicial para a barra de EXP ao redor do perfil de usuário.

## Com 70%
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/86631177/214575008-795fe33c-1ac9-45a1-a7e3-ee50ad14031c.png">

Conversando com o henri, ele me explicou que a feature para EXP no backend ainda estão sendo desenvolvida(como visto aqui https://github.com/he4rt/he4rt-bot-api/issues/19), portanto desenvolvi como um componente para podermos construir sem o backend no momento.

2023-01-26 20:50 UTC, m7he4rt requested changes

2023-01-26 20:50 UTC, m7he4rt commented on app/components/profile/ProfileProgressBar.tsx
> +        </svg>
creio que vai precisar de algumas mudanças no svg. 
![image](https://user-images.githubusercontent.com/44484286/214946877-0eedb5ba-a584-4e6d-8a5c-eb747be4d667.png)
A barra deve começar do lado do Lvl e terminar no número do Lvl 
![image](https://user-images.githubusercontent.com/44484286/214947398-4ed79517-b8b0-4062-93ee-7297dbbbb5cc.png)
no caso desse SVG acho que ele ta considerando o circulo todo

2023-01-26 21:22 UTC, cherryramatisdev commented on app/components/profile/ProfileProgressBar.tsx
> +        </svg>
Ok vou olhar ! vlw

2023-02-04 03:17 UTC, m7he4rt commented on app/components/profile/ProfileProgressBar.tsx
> +        </svg>
@cherryramatisdev tava com um tempo e tomei a liberdade de tentar solucionar o problema, segue a sugestão 
```
type ProfileProgressBarProps = {
  imageSrc: string;
  imageAlt: string;
  percentage: number;
};

export default function ProfileProgressBar({
  imageSrc,
  imageAlt,
  percentage,
}: ProfileProgressBarProps) {
  return (
    <div className='flex h-full w-full items-center justify-center'>
      <div className='relative h-28 w-28 rounded-full'>
        <img
          className='h-full w-full rounded-full border-[5px] border-purple-300'
          src={imageSrc}
          alt={imageAlt}
        />

        <svg
          viewBox='0 0 100 100'
          className='absolute inset-0 h-full w-full rotate-180 scale-[120%]'
        >
          <path
            className='stroke-purple-500 stroke-[5px]'
            id='progress'
            strokeLinecap='round'
            fill='none'
            strokeDasharray={`${(percentage / 100) * 251},251`}
            d='M50 10 a 40 40 0 0 1 0 80 a 40 40 0 0 1 0 -80'
          />
        </svg>
      </div>
    </div>
  );
}
```

2023-02-04 03:28 UTC, cherryramatisdev commented on app/components/profile/ProfileProgressBar.tsx
> +        </svg>
Opa muito obrigada pela sugestão! Passei por períodos bem tensos no trabalho nos últimos dias e não consegui dar atenção para essa issue

vou testar aqui e subir um commit te marcando na solução

2023-02-04 03:38 UTC, cherryramatisdev commented on app/components/profile/ProfileProgressBar.tsx
> +        </svg>
Ficou muito incrível! atualizei os prints e te dei os créditos no commit e na PR

2023-02-05 04:51 UTC, m7he4rt approved these changes

2023-02-05 04:51 UTC, merged