feat: Find at He4rt Section
he4rt/he4rt-landing-ssr pull request #7
Opened 2022-12-19 23:43 UTC by slmeduardo

Desktop:
![image](https://user-images.githubusercontent.com/47526368/208549215-e84ce59f-cbaa-4172-ae69-f7038e605e5c.png)

Mobile:
![image](https://user-images.githubusercontent.com/47526368/208549274-fda5f078-d5b1-4f2b-b458-86369411ccef.png)

2022-12-19 23:54 UTC, kjkGustavo requested changes
Usa `yarn format` antes para conseguirmos seguir com a review.

2022-12-20 03:28 UTC, m7he4rt requested changes

2022-12-20 03:28 UTC, m7he4rt commented on app/components/FindAtHe4rt.tsx
> +        </svg>
Por favor usar o [React Icons](https://react-icons.github.io/react-icons) para os ícones

2022-12-20 03:28 UTC, m7he4rt commented on app/components/FindAtHe4rt.tsx
> +      <p className='text-[#737272] font-sans mt-3 max-w-sm'>{description}</p>
Utilizar as cores que já estão no tema do tailwind.config
```suggestion
      <p className='text-gray-750 font-sans mt-3 max-w-sm'>{description}</p>
```

2022-12-20 03:28 UTC, m7he4rt commented on app/routes/index.tsx
> +            />
Acho melhor criar uma array de props pra fazer esse cara ao invés de ficar repetindo o componente

2022-12-20 03:28 UTC, m7ez1n commented on app/routes/index.tsx
> +      </div>
Componentizar isso em uma section

2022-12-20 03:32 UTC, kjkGustavo commented on app/components/FindAtHe4rt.tsx
> +      <div className='flex gap-3 items-center'>
![image](https://user-images.githubusercontent.com/47262260/208577051-7b90ad85-4571-46ce-ae57-52ee0745676a.png)

Deixar no mobile colado a esquerda. (Creio que seja aqui nessa linha o problema.)

2022-12-21 20:22 UTC, m7he4rt requested changes

2022-12-21 20:22 UTC, m7he4rt commented on app/components/FindAtHe4rtTopic.tsx
> +          style={{
Usar o tailwind nesse component

2022-12-21 20:22 UTC, m7he4rt commented on app/components/FindAtHe4rt.tsx
> +}
Esse componente está duplicado

2022-12-21 20:24 UTC, m7he4rt reviewed
É interessante sempre rodar o comando `yarn format` para deixar os arquivos no padrão do projeto

2022-12-22 17:17 UTC, m7he4rt approved these changes

2022-12-22 22:55 UTC, kjkGustavo approved these changes

2022-12-22 22:55 UTC, JVictorV requested changes

2022-12-22 22:55 UTC, JVictorV commented on tailwind.config.js
> +      },
Porque altterar o tamanho das screens aqui?

2022-12-22 22:56 UTC, kjkGustavo commented on tailwind.config.js
> +      },
não é das screens. é do container

2022-12-23 20:58 UTC, slmeduardo commented on tailwind.config.js
> +      },
> 
Achei que a default ia cortar a imagem do discord, mas não cortou, vou remover e commitar

2022-12-27 19:59 UTC, merged